export const ActionTypes = {
  CHANGE_ACTIVE_CITY: 'change/CHANGE_ACTIVE_CITY',
  CHANGE_OFFERS_OF_CITY: 'change/CHANGE_OFFERS_OF_CITY',
  LOAD_HOTELS: 'load/LOAD_HOTELS',
  LOAD_FAVORITE_HOTELS: 'load/LOAD_FAVORITE_HOTELS',
  REQUIRED_AUTHORIZATION: 'user/REQUIRED_AUTHORIZATION',
  REDIRECT_TO_ROUTE: 'history/REDIRECT_TO_ROUTE',
  LOAD_AUTH_INFO: 'load/LOAD_AUTH_INFO',
};
